routes/web.php
<?php

use App\Http\Controllers\Admin\BlogController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Auth\AdminLoginController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', function () {
    return view('client.home.index');
})->name('home');

Auth::routes();
Route::get('/admin/login', [AdminLoginController::class, 'showLoginForm'])->name('admin.showLoginForm');
// Trang đăng nhập của admin
Route::post('/admin/login', [AdminLoginController::class, 'loginAdmin'])->name('admin.loginAdmin');

// Nhóm routes cho trang admin  (/admin/...)
Route::prefix('/admin')->name('admin.')->middleware(['admin'])->group(function () {
    // Trang chủ của admin (localhost/admin/dashboard)
    Route::get('/dashboard', function () {
        return view('admin.dashboard.index');
    })->name('dashboard');

    
    // Example of protecting a route in routes/web.php
    // Route::middleware(['auth', 'admin'])->group(function () {
    //     Route::get('/admin/dashboard', [AdminController::class, 'dashboard'])->name('admin.dashboard');
    // });

    Route::resource('roles', RoleController::class);
    Route::resource('categories', CategoryController::class);
    Route::resource('blogs', BlogController::class);
    Route::resource('users', UserController::class);
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
    protected $fillable=[
        'name'=> 'required',
        'parent_id'=> null
    ];

    static function getParents()
    {
        return [];
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = [];

        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        $parentCategories = Category::getParents();
        return view('admin.categories.create', compact('parentCategories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CreateBlogRequest $request
     * @return RedirectResponse
     */
    public function store(Request $request)
    {
        return redirect()->route('admin.categories.index') ->with(['messege' => 'Create category success']) ;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // $role = $this->roleService->findOrFail($id);
    }

    /**
     * Update the specified resource in storage.
     *
     *  @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
    
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
    
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.app')
@section('title', 'Create Category')
@section('content')
    <div class="card">
        <h1>Create Category</h1>
        <div>
            <form action="{{ route('admin.categories.store') }}" method="post">
                @csrf
                <div class="input-group input-group-static mb-4">
                    <label>Name</label>
                    <input type="text" value="{{ old('name') }}" name="name" class="form-control">

                    @error('name')
                        <span class="text-danger"> {{ $message }}</span>
                    @enderror
                </div>

                <div class="input-group input-group-static mb-4">
                    <label>Display Name</label>
                    <input type="text" value="{{ old('display_name') }}" name="display_name" class="form-control">
                    @error('display_name')
                        <span class="text-danger"> {{ $message }}</span>
                    @enderror
                </div>

                <div class="input-group input-group-static mb-4">
                    <label name="group" class="ms-0">Parent Category</label>
                    <select name="parent_id" class="form-control">
                        <option value=""> Select Parent Category </option>
                        @foreach ($parentCategories as $item)
                            <option value="{{ $item->id }}" {{ old('parent_id') == $item->id ? 'selected' : '' }}>
                                {{ $item->name }}</option>
                        @endforeach
                    </select>
                </div>

                <button type="submit" class="btn btn-submit btn-primary">Submit</button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.app')
@section('title', 'Edit Roles ' . $role->name)
@section('content')
    <div class="card">
        <h1>Edit role</h1>

        <div>
            <form action="{{ route('admin.roles.update', $role->id) }}" method="post">
                @csrf
                @method('PUT')


                <div class="input-group input-group-static mb-4">
                    <label>Name</label>
                    <input type="text" value="{{ old('name') ?? $role->name }}" name="name" class="form-control">

                    @error('name')
                        <span class="text-danger"> {{ $message }}</span>
                    @enderror
                </div>

                <div class="input-group input-group-static mb-4">
                    <label>Display Name</label>
                    <input type="text" value="{{ old('display_name') ?? $role->display_name }}" name="display_name"
                        class="form-control">
                    @error('display_name')
                        <span class="text-danger"> {{ $message }}</span>
                    @enderror
                </div>

                <div class="input-group input-group-static mb-4">
                    <label name="group" class="ms-0">Group</label>
                    <select name="group" class="form-control" value={{ $role->group }}>
                        <option value="system">System</option>
                        <option value="user">User</option>

                    </select>

                    @error('group')
                        <span class="text-danger"> {{ $message }}</span>
                    @enderror
                </div>


                <div class="form-group">
                    <label for="">Permission</label>
                    <div class="row">
                        @foreach ($permissions as $groupName => $permission)
                            <div class="col-5">
                                <h4>{{ $groupName }}</h4>

                                <div>
                                    @foreach ($permission as $item)
                                        <div class="form-check">
                                            <input class="form-check-input" name="permission_ids[]" type="checkbox"
                                                {{ $role->permissions->contains('name', $item->name) ? 'checked' : '' }}
                                                value="{{ $item->id }}">
                                            <label class="custom-control-label"
                                                for="customCheck1">{{ $item->display_name }}</label>
                                        </div>
                                    @endforeach
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>

                <button type="submit" class="btn btn-submit btn-primary">Submit</button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.app')
@section('title', 'Categories')
@section('content')
    <div class="card">
        <h1>
            Category list
        </h1>
        @if (session('message'))
        <h1 class="text-primary">{{ session('message') }}</h1>
        @endif
        <div>
            <a href="{{ route('admin.categories.create') }}" class="btn btn-primary">Create</a>
        </div>
        <div>
            <table class="table table-hover">
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Parent Name</th>
                    <th>Action</th>
                </tr>

                @foreach ($categories as $item)
                    <tr>
                        <td>{{ $item->id }}</td>
                        <td>{{ $item->name }}</td>

                        <td>{{ $item->parent_name }}</td>
                        <td>
                            @can('update-category')
                                <a href="{{ route('categories.edit', $item->id) }}" class="btn btn-warning">Edit</a>
                            @endcan
                            @can('delete-category')
                                <form action="{{ route('categories.destroy', $item->id) }}"
                                    id="form-delete{{ $item->id }}" method="post">
                                    @csrf
                                    @method('delete')

                                </form>
                                <button class="btn btn-delete btn-danger" data-id={{ $item->id }}>Delete</button>
                            @endcan

                        </td>
                    </tr>

                @endforeach
            </table>
            {{-- {{ $roles->links() }} --}}
        </div>

    </div>

@endsection