routes/web.php
<?php

use App\Http\Controllers\Admin\BlogController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Auth\AdminLoginController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', function () {
    return view('client.home.index');
})->name('home');

Auth::routes();
Route::get('/admin/login', [AdminLoginController::class, 'showLoginForm'])->name('admin.showLoginForm');
// Trang đăng nhập của admin
Route::post('/admin/login', [AdminLoginController::class, 'loginAdmin'])->name('admin.loginAdmin');

// Nhóm routes cho trang admin  (/admin/...)
Route::prefix('/admin')->name('admin.')->middleware(['admin'])->group(function () {
    // Trang chủ của admin (localhost/admin/dashboard)
    Route::get('/dashboard', function () {
        return view('admin.dashboard.index');
    })->name('dashboard');

    
    // Example of protecting a route in routes/web.php
    // Route::middleware(['auth', 'admin'])->group(function () {
    //     Route::get('/admin/dashboard', [AdminController::class, 'dashboard'])->name('admin.dashboard');
    // });

    Route::resource('roles', RoleController::class);
    Route::resource('categories', CategoryController::class);
    Route::resource('blogs', BlogController::class);
    Route::resource('users', UserController::class);
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Log;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'gender',
        'date_of_birth',
        'phone',
        'is_admin'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    static function store($data) {
        try {
            // Tạo mới đối tượng User
            $user = new self; 
            // Mã hoá password ra chuỗi kí tự đặc biệt               
            $data['password'] = Hash::make($data['password']);
            // Lưu vào database
            if ($user->create($data)) {
                return true;
            } else {
                return false;
            }    
        } catch (\Exception $e) {
            // Nếu xảy ra bất cứ lỗi gì sẽ log lỗi ra file log
            Log::error($e);
            return [
                'success' => false,
                'message' => 'Something went wrong!'
            ];
        }
    }
    
    static function updateAdmin($request, $id) {
        try {
            $dataUpdate = $request->except('password');
            $user = self::findOrFail($id);
            if ($request->password) {
                $dataCreate['password'] = Hash::make($request->password);
            }
            
            // Lưu vào database
            if ($user->update($dataUpdate)) {
                $user->assignRoles($dataUpdate['role_ids'] ?? []);
                return [
                    'success' => true,
                    'message' => 'Update admin successfully!',
                    'data' => $user
                ];
            } else {
                return [
                    'success' => false,
                    'message' => 'Update admin failure!'
                ];
            }    
        } catch (\Exception $e) {
            // Nếu xảy ra bất cứ lỗi gì sẽ log lỗi ra file log
            Log::error($e);
        }
    }

    // static function findByEmailAndPassword($data) {
    //     try {
    //         $user = self::where('email', $data['email'])->where('password', $data['password'])->get();
    //         if (isset($user) && !empty($user)) {
    //             return $user;
    //         } else {
    //             return false;
    //         }
    //     } catch (\Exception $e) {
    //         Log::error($e);
    //     }
    // }


    /**
     * @param array|int $roles
     * @return array
     */
    public function assignRoles($roles)
    {
        return $this->roles()->sync($roles);
    }

    static function allAdmin() {
        return self::where('is_admin', 1)->get();
        // return self::where('is_admin', 1)->where('id', '<>', 1)->get();
    }

    static function storeAdmin($data) {
        try {
            // Tạo mới đối tượng User
            $user = new self;
            $data['is_admin'] = 1;
            // Mã hoá password ra chuỗi kí tự đặc biệt               
            $data['password'] = Hash::make($data['password']);
            // Save admin
            $user = $user->create($data);
            if ($user) {
                $user->assignRoles($data['role_ids'] ?? []);
                return [
                    'success' => true,
                    'message' => 'Create admin successfully!',
                    'data' => $user
                ];
            } else {
                return [
                    'success' => false,
                    'message' => 'Create admin failure!'
                ];
            }
            $user->assignRoles($data['role_ids'] ?? []);
        } catch (\Exception $e) {
            dd($e);
            return [
                'success' => false,
                'message' => 'Something went wrong!'
            ];
            // Nếu xảy ra bất cứ lỗi gì sẽ log lỗi ra file log
            Log::error($e);
        }
    }

}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Middleware\RedirectIfAuthenticated;
use App\Http\Requests\AdminStoreRequest;
use App\Http\Requests\UpdateUserRequest;
use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::allAdmin();
        return view('admin.user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::getWithGroup();
        return view('admin.user.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AdminStoreRequest $request)
    {
        $dataCreate = $request->except(['_token']);
        $result = User::storeAdmin($dataCreate);
        if ($result['success']) {
            $user = $result['data'];
            $message = $result['message'] . ' ('. $user->name .')';
            return redirect()->route('admin.users.index')->with('message', $message);
        } else {
            return redirect()->back()->with('error', $result['message']);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id)->load('roles');
        $roles = Role::getWithGroup();

        return view('admin.user.edit', compact('user', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUserRequest $request, $id)
    {
        $result = User::updateAdmin($request, $id);
        if ($result['success']) {
            $user = $result['data'];
            $message = $result['message'] . ' ('. $user->name .')';
            return redirect()->route('admin.users.index')->with('message', $message);
        } else {
            return redirect()->back()->with('error', $result['message']);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (User::destroy($id)) {
            return redirect()->route('admin.users.index')->with(['message' => 'Delete admin suceess!']);
        } else {
            return redirect()->back()->with(['message' => 'Delete admin failure!']);
        }
    }
}

resources/views/admin/user/create.blade.php
@extends('admin.layouts.app')
@section('title', 'Create User')
@section('content')
    <div class="card">
        <h1>Create User</h1>
        @if (session('error'))
        <div class="alert alert-danger alert-dismissible text-white" role="alert">
            <span class="text-sm">{{ session('error') }}</span>
            <button type="button" class="btn-close text-lg py-3 opacity-10" data-bs-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
            </button>
        </div>
        @endif
        <div>
            <form action="{{ route('admin.users.store') }}" method="post" enctype="multipart/form-data">
                @csrf

                <div class="input-group input-group-static mb-4">
                    <label>Name</label>
                    <input type="text" value="{{ old('name') }}" name="name" class="form-control">

                    @error('name')
                        <span class="text-danger"> {{ $message }}</span>
                    @enderror
                </div>

                <div class="input-group input-group-static mb-4">
                    <label>Email</label>
                    <input type="email" value="{{ old('email') }}" name="email" class="form-control" autocomplete="off">
                    @error('email')
                        <span class="text-danger"> {{ $message }}</span>
                    @enderror
                </div>

                <div class="input-group input-group-static mb-4">
                    <label>Phone</label>
                    <input type="text" value="{{ old('phone') }}" name="phone" class="form-control">
                    @error('phone')
                        <span class="text-danger"> {{ $message }}</span>
                    @enderror
                </div>

                <div class="input-group input-group-static mb-4">
                    <label class="ms-0">Gender</label>
                    <select name="gender" class="form-control">
                        <option value="male">Male</option>
                        <option value="female">FeMale</option>
                    </select>

                    @error('gender')
                        <span class="text-danger"> {{ $message }}</span>
                    @enderror
                </div>

                <div class="input-group input-group-static mb-4">
                    <label>Date of birth</label>
                    <input type="date" name="date_of_birth" class="form-control" value="{{ old('date_of_birth') }}"> 
                    @error('date_of_birth')
                        <span class="text-danger"> {{ $message }}</span>
                    @enderror
                </div>

                <div class="input-group input-group-static mb-4">
                    <label>Password</label>
                    <input type="password" name="password" class="form-control" autocomplete="off">
                    @error('password')
                        <span class="text-danger"> {{ $message }}</span>
                    @enderror
                </div>

                <div class="input-group input-group-static mb-4">
                    <label>Confirm password</label>
                    <input type="password" name="confirm_password" class="form-control" autocomplete="off">
                    @error('confirm_password')
                        <span class="text-danger"> {{ $message }}</span>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="">Roles</label>
                    <div class="row">
                        @foreach ($roles as $groupName => $role)
                            <div class="col-5">
                                <h4>{{ $groupName }}</h4>

                                <div>
                                    @foreach ($role as $item)
                                        <div class="form-check">
                                            <input class="form-check-input" name="role_ids[]" type="checkbox"
                                                value="{{ $item->id }}">
                                            <label class="custom-control-label"
                                                for="customCheck1">{{ $item->display_name }}</label>
                                        </div>
                                    @endforeach
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>


                <button type="submit" class="btn btn-submit btn-primary">Submit</button>
            </form>
        </div>
    </div>
@endsection


@section('script')

    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
        crossorigin="anonymous"></script>
    <script>
        $(() => {
            function readURL(input) {
                if (input.files && input.files[0]) {
                    var reader = new FileReader();
                    reader.onload = function(e) {
                        $('#show-image').attr('src', e.target.result);
                    };
                    reader.readAsDataURL(input.files[0]);
                }
            }

            $("#image-input").change(function() {
                readURL(this);
            });
        });
    </script>
@endsection

resources/views/admin/user/edit.blade.php
@extends('admin.layouts.app')
@section('title', 'Create User')
@section('content')
    <div class="card">
        <h3>Update User {{ $user->name }}</h1>
        @if (session('error'))
        <div class="alert alert-danger alert-dismissible text-white" role="alert">
            <span class="text-sm">{{ session('error') }}</span>
            <button type="button" class="btn-close text-lg py-3 opacity-10" data-bs-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
            </button>
        </div>
        @endif
        <div>
            <form action="{{ route('admin.users.update', $user->id) }}" method="post" enctype="multipart/form-data">
                @csrf
                @method('put')

                <div class="input-group input-group-static mb-4">
                    <label>Name</label>
                    <input type="text" value="{{ old('name') ?? $user->name  }}" name="name" class="form-control">

                    @error('name')
                        <span class="text-danger"> {{ $message }}</span>
                    @enderror
                </div>

                <div class="input-group input-group-static mb-4">
                    <label>Email</label>
                    <input type="email" value="{{ old('email') ?? $user->email }}" name="email" class="form-control" autocomplete="off">
                    @error('email')
                        <span class="text-danger"> {{ $message }}</span>
                    @enderror
                </div>

                <div class="input-group input-group-static mb-4">
                    <label>Phone</label>
                    <input type="text" value="{{ old('phone') ?? $user->phone }}" name="phone" class="form-control">
                    @error('phone')
                        <span class="text-danger"> {{ $message }}</span>
                    @enderror
                </div>

                <div class="input-group input-group-static mb-4">
                    <label class="ms-0">Gender</label>
                    <select name="gender" class="form-control">
                        <option value="male">Male</option>
                        <option value="female">FeMale</option>
                    </select>

                    @error('gender')
                        <span class="text-danger"> {{ $message }}</span>
                    @enderror
                </div>

                <div class="input-group input-group-static mb-4">
                    <label>Date of birth</label>
                    <input type="date" name="date_of_birth" class="form-control" value="{{ old('date_of_birth') ?? $user->date_of_birth }}"> 
                    @error('date_of_birth')
                        <span class="text-danger"> {{ $message }}</span>
                    @enderror
                </div>

                <div class="input-group input-group-static mb-4">
                    <label>Password</label>
                    <input type="password" name="password" class="form-control" autocomplete="off">
                    @error('password')
                        <span class="text-danger"> {{ $message }}</span>
                    @enderror
                </div>

                <div class="input-group input-group-static mb-4">
                    <label>Confirm password</label>
                    <input type="password" name="confirm_password" class="form-control" autocomplete="off">
                    @error('confirm_password')
                        <span class="text-danger"> {{ $message }}</span>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="">Roles</label>
                    <div class="row">
                        @foreach ($roles as $groupName => $role)
                            <div class="col-5">
                                <h4>{{ $groupName }}</h4>
                                
                                <div>
                                    @foreach ($role as $item)
                                        @if($item->id == 1)
                                            @hasrole('super-admin')
                                            <div class="form-check">
                                                <input class="form-check-input" name="role_ids[]"
                                                    {{ $user->roles->contains('id', $item->id) ? 'checked' : '' }}
                                                    type="checkbox" value="{{ $item->id }}">
                                                <label class="custom-control-label"
                                                    for="customCheck1">{{ $item->display_name }}</label>
                                            </div>
                                            @endhasrole
                                        @else
                                            <div class="form-check">
                                                <input class="form-check-input" name="role_ids[]"
                                                    {{ $user->roles->contains('id', $item->id) ? 'checked' : '' }}
                                                    type="checkbox" value="{{ $item->id }}">
                                                <label class="custom-control-label"
                                                    for="customCheck1">{{ $item->display_name }}</label>
                                            </div>
                                        @endif
                                    @endforeach
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>


                <button type="submit" class="btn btn-submit btn-primary">Submit</button>
            </form>
        </div>
    </div>
@endsection


@section('script')

    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
        crossorigin="anonymous"></script>
    <script>
        $(() => {
            function readURL(input) {
                if (input.files && input.files[0]) {
                    var reader = new FileReader();
                    reader.onload = function(e) {
                        $('#show-image').attr('src', e.target.result);
                    };
                    reader.readAsDataURL(input.files[0]);
                }
            }

            $("#image-input").change(function() {
                readURL(this);
            });
        });
    </script>
@endsection

resources/views/admin/user/index.blade.php
@extends('admin.layouts.app')
@section('title', 'Users')
@section('content')
    <div class="card">

        <h1>
            User list
        </h1>
        @if (session('message'))
            <div class="alert alert-success alert-dismissible text-white" role="alert">
                <span class="text-sm">{{ session('message') }}</span>
                <button type="button" class="btn-close text-lg py-3 opacity-10" data-bs-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
                </button>
            </div>
        @endif
        <div>
            <a href="{{ route('admin.users.create') }}" class="btn btn-primary">Create</a>
        </div>
        <div>
            <table class="table table-hover">
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Action</th>
                </tr>

                @foreach ($users as $item)
                    <tr>
                        <td>{{ $item->id }}</td>
                        <td>{{ $item->name }}</td>
                        <td>{{ $item->email }}</td>
                        <td>{{ $item->phone }}</td>
                        <td class="d-flex" style="gap: 1rem">
                            {{-- @can('update-user') --}}
                                <a href="{{ route('admin.users.edit', $item->id) }}" class="btn btn-warning mr-1"><i class="material-icons opacity-10">edit</i></a>
                            {{-- @endcan --}}
                            {{-- @can('delete-user') --}}
                                <form action="{{ route('admin.users.destroy', $item->id) }}" id="form-delete{{ $item->id }}"
                                    method="post">
                                    @csrf
                                    @method('delete')
                                    <button class="btn btn-delete btn-danger" type="submit"
                                        data-id={{ $item->id }}><i class="material-icons opacity-10">delete</i></button>
                                </form>
                            {{-- @endcan --}}
                        </td>
                    </tr>
                @endforeach
            </table>
            {{-- {{ $users->links() }} --}}
        </div>

    </div>

@endsection

@section('script')
@endsection